output_dir: "./saved_models"
tokenizer_name: "microsoft/codebert-base"
model_name_or_path: "microsoft/codebert-base"
do_train: True
do_test: True
train_data_file: "./datasets/1/train.jsonl"
eval_data_file: "./datasets/1/test.jsonl"
test_data_file: "./datasets/1/test.jsonl"
num_train_epochs: 7
block_size: 256
train_batch_size: 8
eval_batch_size: 16
learning_rate: 0.00002
max_grad_norm: 1.0
num_labels: 4
weight_decay: 0.0
adam_epsilon: 0.00000001
warmup_steps: 0